services:
  - type: worker
    name: telegram-qr-bot
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update -y && apt-get install -y libzbar0 zbar-tools python3-dev build-essential
      pip install --upgrade pip wheel setuptools
      pip install pyTelegramBotAPI==4.14.0 pyzbar==0.1.9 opencv-python-headless==4.8.0.74 Pillow==9.5.0 numpy==1.24.3 requests==2.31.0 python-dotenv==1.0.0 google-generativeai==0.3.2
    startCommand: python run_telegram_bot.py
    runtime: python3
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PATH
        value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin