services:
  - type: worker
    name: telegram-qr-bot
    env: python
    region: oregon
    plan: free
    buildCommand: chmod +x install_dependencies.sh && ./install_dependencies.sh
    startCommand: python run_telegram_bot.py
    runtime: python3
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PATH
        value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin